name: cf workers

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "LICENSE.md"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cf
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
# Error:
#       Compiling siren v0.1.0 (/home/runner/work/BlueHat358-Kirlia/BlueHat358-Kirlia)
#   error[E0599]: no method named `post_with_headers` found for enum `worker::Fetch` in the current scope
#     --> src/proxy/dns.rs:10:10
#      |
#    9 |       let mut response = Fetch::Url(Url::parse("https://1.1.1.1/dns-query")?)
#      |  ________________________-
#   10 | |         .post_with_headers(req_wireformat, headers)?
#      | |         -^^^^^^^^^^^^^^^^^ method not found in `worker::Fetch`
#      | |_________|
#      |
#   warning: variable does not need to be mutable
#     --> src/proxy/dns.rs:59:21
#      |
#   59 |                 let mut headers = Headers::new();
#      |                     ----^^^^^^^
#      |                     |
#      |                     help: remove this `mut`
#      |
#      = note: `#[warn(unused_mut)]` (part of `#[warn(unused)]`) on by default
#   warning: variable does not need to be mutable
#     --> src/proxy/dns.rs:68:9
#      |
#   68 |     let mut headers = Headers::new();
#      |         ----^^^^^^^
#      |         |
#      |         help: remove this `mut`
#   For more information about this error, try `rustc --explain E0599`.
#   warning: `siren` (lib) generated 2 warnings
#   error: could not compile `siren` (lib) due to 1 previous error; 2 warnings emitted
#   Error: Compiling your crate to WebAssembly failed
#   Caused by:
#       failed to execute `cargo build`: exited with exit status: 101
#         full command: cd "/home/runner/work/BlueHat358-Kirlia/BlueHat358-Kirlia" && "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"
#   ✘ [ERROR] Running custom build `cargo install worker-build && worker-build --release` failed. There are likely more logs from your build command above.
#   🪵  Logs were written to "/home/runner/.config/.wrangler/logs/wrangler-2025-12-04_03-29-32_180.log"
# Error: The process '/usr/local/bin/npx' failed with exit code 1
# Error: 🚨 Action failed
